/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RES0

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "Config0.h"

#include "POUS.c"

BOOL TASKMAIN;
MY_PROGRAM RES0__INST0;
#define INST0 RES0__INST0

void RES0_init__(void) {
  BOOL retain;
  retain = 0;
  
  TASKMAIN = __BOOL_LITERAL(FALSE);
  MY_PROGRAM_init__(&INST0,retain);
}

void RES0_run__(unsigned long tick) {
  TASKMAIN = !(tick % 1);
  if (TASKMAIN) {
    MY_PROGRAM_body__(&INST0);
  }
}

